version: '3'

services:
  rendasolidaria.api:
    image: rendasolidariaapi:latest
    container_name: rendasolidaria_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8080:80"
      - "8081:443"
    environment: 
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes: 
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rendasolidariadb
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    # networks:
    #   - postgres-compose-network

#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: db
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "16543:80"
#     depends_on:
#       - db
#     networks:
#       - postgres-compose-network

# networks: 
#   postgres-compose-network:
#     driver: bridge